import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.9"

    const val com_github_danbrough_androidutils: String = "1.1.0-beta08"

    const val com_github_danbrough_exoplayer: String = "2.11.0-dan03"

    const val com_github_bumptech_glide: String = "4.11.0"

    const val androidx_navigation: String =  "2.3.0"

    const val androidx_lifecycle: String =  "2.2.0"

    const val androidx_multidex: String = "2.0.0"

    const val ch_qos_logback: String = "1.2.3"

    const val androidx_room: String = "2.2.5"

    const val androidx_test: String = "1.3.0"

    const val com_android_tools_build_gradle: String = "4.1.0-rc02"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val kotlin_annotation_processing_gradle: String = "1.4.0"

    const val kotlin_android_extensions_runtime: String = "1.4.0"

    const val kotlin_android_extensions: String = "1.4.0"

    const val kotlin_gradle_plugin: String =  "1.4.0"

    const val kotlin_stdlib_jdk8: String =  "1.4.0"

    const val constraintlayout: String =  "2.0.1"

    const val kotlin_reflect: String =  "1.4.0"

    const val preference_ktx: String = "1.1.1"

    const val mockito_core: String = "3.5.9"

    const val lint_gradle: String = "27.1.0-rc02"

    const val robolectric: String = "4.4"

    const val slf4j_api: String = "1.7.30"

    const val core_ktx: String = "1.3.1"

    const val material: String = "1.2.0"

    const val library: String = "3.4.0"

    const val okhttp: String = "4.8.1"

    const val aapt2: String = "4.1.0-rc02-6503028"

    const val junit: String = "4.13"

    const val gson: String = "2.8.6"

    /**
     * Current version: "6.6.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.6.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
