import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.2-1.3.60"

    const val com_github_danbrough_androidutils: String = "1.0.15"

    const val com_github_danbrough_exoplayer: String = "2.11.0-dan03"

    const val com_github_bumptech_glide: String = "4.10.0"

    const val org_jetbrains_kotlin: String = "1.3.61"

    const val androidx_navigation: String = "2.2.0-rc02"

    const val androidx_lifecycle: String = "2.2.0-rc02"

    const val androidx_multidex: String = "2.0.0"

    const val ch_qos_logback: String = "1.2.3"

    const val androidx_room: String = "2.2.2"

    const val androidx_test: String = "1.2.0"

    const val com_android_tools_build_gradle: String = "3.6.0-beta04"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val constraintlayout: String = "1.1.3"

    const val preference_ktx: String = "1.1.0"

    const val mockito_core: String = "3.2.0"

    const val lint_gradle: String = "26.6.0-beta04"

    const val robolectric: String = "4.3.1"

    const val slf4j_api: String = "1.7.29"

    const val core_ktx: String = "1.2.0-beta01"

    const val material: String = "1.0.0"

    const val library: String = "3.4.0"

    const val okhttp: String = "4.2.2"

    const val aapt2: String = "3.6.0-beta04-5836729"

    const val junit: String = "4.12"

    const val gson: String = "2.8.6"

    /**
     * Current version: "6.0.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.0.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
